/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_learn_jni_DataProvider_Companion */

#ifndef _Included_com_learn_jni_DataProvider_Companion
#define _Included_com_learn_jni_DataProvider_Companion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
