/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_learn_jni_DataProvider */

#ifndef _Included_com_learn_jni_DataProvider
#define _Included_com_learn_jni_DataProvider
#ifdef __cplusplus
extern "C" {
#endif
#undef com_learn_jni_DataProvider_BIND_ABOVE_CLIENT
#define com_learn_jni_DataProvider_BIND_ABOVE_CLIENT 8L
#undef com_learn_jni_DataProvider_BIND_ADJUST_WITH_ACTIVITY
#define com_learn_jni_DataProvider_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_learn_jni_DataProvider_BIND_ALLOW_OOM_MANAGEMENT
#define com_learn_jni_DataProvider_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_learn_jni_DataProvider_BIND_AUTO_CREATE
#define com_learn_jni_DataProvider_BIND_AUTO_CREATE 1L
#undef com_learn_jni_DataProvider_BIND_DEBUG_UNBIND
#define com_learn_jni_DataProvider_BIND_DEBUG_UNBIND 2L
#undef com_learn_jni_DataProvider_BIND_EXTERNAL_SERVICE
#define com_learn_jni_DataProvider_BIND_EXTERNAL_SERVICE -2147483648L
#undef com_learn_jni_DataProvider_BIND_IMPORTANT
#define com_learn_jni_DataProvider_BIND_IMPORTANT 64L
#undef com_learn_jni_DataProvider_BIND_INCLUDE_CAPABILITIES
#define com_learn_jni_DataProvider_BIND_INCLUDE_CAPABILITIES 4096L
#undef com_learn_jni_DataProvider_BIND_NOT_FOREGROUND
#define com_learn_jni_DataProvider_BIND_NOT_FOREGROUND 4L
#undef com_learn_jni_DataProvider_BIND_NOT_PERCEPTIBLE
#define com_learn_jni_DataProvider_BIND_NOT_PERCEPTIBLE 256L
#undef com_learn_jni_DataProvider_BIND_WAIVE_PRIORITY
#define com_learn_jni_DataProvider_BIND_WAIVE_PRIORITY 32L
#undef com_learn_jni_DataProvider_CONTEXT_IGNORE_SECURITY
#define com_learn_jni_DataProvider_CONTEXT_IGNORE_SECURITY 2L
#undef com_learn_jni_DataProvider_CONTEXT_INCLUDE_CODE
#define com_learn_jni_DataProvider_CONTEXT_INCLUDE_CODE 1L
#undef com_learn_jni_DataProvider_CONTEXT_RESTRICTED
#define com_learn_jni_DataProvider_CONTEXT_RESTRICTED 4L
#undef com_learn_jni_DataProvider_MODE_APPEND
#define com_learn_jni_DataProvider_MODE_APPEND 32768L
#undef com_learn_jni_DataProvider_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_learn_jni_DataProvider_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_learn_jni_DataProvider_MODE_MULTI_PROCESS
#define com_learn_jni_DataProvider_MODE_MULTI_PROCESS 4L
#undef com_learn_jni_DataProvider_MODE_NO_LOCALIZED_COLLATORS
#define com_learn_jni_DataProvider_MODE_NO_LOCALIZED_COLLATORS 16L
#undef com_learn_jni_DataProvider_MODE_PRIVATE
#define com_learn_jni_DataProvider_MODE_PRIVATE 0L
#undef com_learn_jni_DataProvider_MODE_WORLD_READABLE
#define com_learn_jni_DataProvider_MODE_WORLD_READABLE 1L
#undef com_learn_jni_DataProvider_MODE_WORLD_WRITEABLE
#define com_learn_jni_DataProvider_MODE_WORLD_WRITEABLE 2L
#undef com_learn_jni_DataProvider_RECEIVER_VISIBLE_TO_INSTANT_APPS
#define com_learn_jni_DataProvider_RECEIVER_VISIBLE_TO_INSTANT_APPS 1L
#undef com_learn_jni_DataProvider_DEFAULT_KEYS_DIALER
#define com_learn_jni_DataProvider_DEFAULT_KEYS_DIALER 1L
#undef com_learn_jni_DataProvider_DEFAULT_KEYS_DISABLE
#define com_learn_jni_DataProvider_DEFAULT_KEYS_DISABLE 0L
#undef com_learn_jni_DataProvider_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_learn_jni_DataProvider_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef com_learn_jni_DataProvider_DEFAULT_KEYS_SEARCH_LOCAL
#define com_learn_jni_DataProvider_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_learn_jni_DataProvider_DEFAULT_KEYS_SHORTCUT
#define com_learn_jni_DataProvider_DEFAULT_KEYS_SHORTCUT 2L
#undef com_learn_jni_DataProvider_RESULT_CANCELED
#define com_learn_jni_DataProvider_RESULT_CANCELED 0L
#undef com_learn_jni_DataProvider_RESULT_FIRST_USER
#define com_learn_jni_DataProvider_RESULT_FIRST_USER 1L
#undef com_learn_jni_DataProvider_RESULT_OK
#define com_learn_jni_DataProvider_RESULT_OK -1L
#undef com_learn_jni_DataProvider_MAX_NUM_PENDING_FRAGMENT_ACTIVITY_RESULTS
#define com_learn_jni_DataProvider_MAX_NUM_PENDING_FRAGMENT_ACTIVITY_RESULTS 65534L
#undef com_learn_jni_DataProvider_MSG_RESUME_PENDING
#define com_learn_jni_DataProvider_MSG_RESUME_PENDING 2L
/*
 * Class:     com_learn_jni_DataProvider
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_learn_jni_DataProvider_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_learn_jni_DataProvider
 * Method:    stringFromJNI2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_learn_jni_DataProvider_stringFromJNI2
  (JNIEnv *, jobject);

/*
 * Class:     com_learn_jni_DataProvider
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_learn_jni_DataProvider_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_learn_jni_DataProvider
 * Method:    sayHelloInC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_learn_jni_DataProvider_sayHelloInC
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_learn_jni_DataProvider
 * Method:    callInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_learn_jni_DataProvider_callInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_learn_jni_DataProvider
 * Method:    callFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_learn_jni_DataProvider_callFromJava
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
