/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_learn_jni_DataProvider */

#ifndef _Included_com_learn_jni_DataProvider
#define _Included_com_learn_jni_DataProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_learn_jni_DataProvider
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_learn_jni_DataProvider_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_learn_jni_DataProvider
 * Method:    stringFromJNI2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_learn_jni_DataProvider_stringFromJNI2
  (JNIEnv *, jobject);

/*
 * Class:     com_learn_jni_DataProvider
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_learn_jni_DataProvider_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_learn_jni_DataProvider
 * Method:    sayHelloInC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_learn_jni_DataProvider_sayHelloInC
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_learn_jni_DataProvider
 * Method:    callInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_learn_jni_DataProvider_callInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_learn_jni_DataProvider
 * Method:    callFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_learn_jni_DataProvider_callFromJava
  (JNIEnv *, jobject);

/*
 * Class:     com_learn_jni_DataProvider
 * Method:    getPressure
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_learn_jni_DataProvider_getPressure
  (JNIEnv *, jobject);

/*
 * Class:     com_learn_jni_DataProvider
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_learn_jni_DataProvider_getLameVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_learn_jni_DataProvider
 * Method:    convertAudio
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_learn_jni_DataProvider_convertAudio
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_learn_jni_DataProvider
 * Method:    addFloat
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_learn_jni_DataProvider_addFloat
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
